# IPC to BNS mapping with min/max sentences
IPC_BNS_MAP = {
    "302": {"bns": "101", "offense": "Murder", "min": "Death or Life Imprisonment", "max": "Death"},
    "304": {"bns": "105", "offense": "Culpable Homicide", "min": "10 years", "max": "Life Imprisonment"},
    "307": {"bns": "109", "offense": "Attempt to Murder", "min": "10 years", "max": "Life Imprisonment"},
    "323": {"bns": "115", "offense": "Voluntarily Causing Hurt", "min": "1 year", "max": "1 year"},
    "324": {"bns": "117", "offense": "Hurt by Dangerous Weapons", "min": "3 years", "max": "3 years"},
    "325": {"bns": "117", "offense": "Grievous Hurt", "min": "7 years", "max": "7 years"},
    "326": {"bns": "118", "offense": "Grievous Hurt by Dangerous Weapons", "min": "10 years", "max": "Life Imprisonment"},
    "354": {"bns": "74", "offense": "Assault on Woman", "min": "1 year", "max": "5 years"},
    "375": {"bns": "63", "offense": "Rape", "min": "10 years", "max": "Life Imprisonment"},
    "376": {"bns": "64", "offense": "Punishment for Rape", "min": "10 years", "max": "Life Imprisonment"},
    "379": {"bns": "303", "offense": "Theft", "min": "3 years", "max": "3 years"},
    "380": {"bns": "305", "offense": "Theft in Dwelling", "min": "7 years", "max": "7 years"},
    "382": {"bns": "304", "offense": "Theft after preparation to cause death", "min": "10 years", "max": "10 years"},
    "383": {"bns": "308", "offense": "Extortion", "min": "3 years", "max": "3 years"},
    "384": {"bns": "308", "offense": "Punishment for Extortion", "min": "3 years", "max": "3 years"},
    "392": {"bns": "309", "offense": "Robbery", "min": "10 years", "max": "10 years"},
    "395": {"bns": "310", "offense": "Dacoity", "min": "Life Imprisonment", "max": "Life Imprisonment"},
    "396": {"bns": "310", "offense": "Dacoity with Murder", "min": "Life Imprisonment", "max": "Death"},
    "406": {"bns": "316", "offense": "Criminal Breach of Trust", "min": "3 years", "max": "3 years"},
    "420": {"bns": "318", "offense": "Cheating", "min": "7 years", "max": "7 years"},
    "426": {"bns": "324", "offense": "Mischief", "min": "3 months", "max": "3 months"},
    "427": {"bns": "324", "offense": "Mischief causing damage", "min": "2 years", "max": "2 years"},
    "447": {"bns": "329", "offense": "Criminal Trespass", "min": "3 months", "max": "3 months"},
    "448": {"bns": "330", "offense": "House Trespass", "min": "1 year", "max": "1 year"},
    "498A": {"bns": "85", "offense": "Cruelty by Husband/Relatives", "min": "3 years", "max": "3 years"},
    "499": {"bns": "356", "offense": "Defamation", "min": "2 years", "max": "2 years"},
    "500": {"bns": "356", "offense": "Punishment for Defamation", "min": "2 years", "max": "2 years"},
    "504": {"bns": "352", "offense": "Intentional Insult", "min": "2 years", "max": "2 years"},
    "506": {"bns": "351", "offense": "Criminal Intimidation", "min": "2 years", "max": "7 years"},
    "509": {"bns": "79", "offense": "Word/Gesture to insult woman", "min": "3 years", "max": "3 years"},
    "34":  {"bns": "3(5)", "offense": "Common Intention", "min": "Same as main offense", "max": "Same as main offense"},
    "107": {"bns": "45", "offense": "Abetment", "min": "Same as main offense", "max": "Same as main offense"},
    "120B": {"bns": "61", "offense": "Criminal Conspiracy", "min": "6 months", "max": "Life Imprisonment"},
    "121": {"bns": "147", "offense": "Waging war against India", "min": "Life Imprisonment", "max": "Death"},
    "124A": {"bns": "152", "offense": "Sedition/Acts against sovereignty", "min": "3 years", "max": "Life Imprisonment"},
    "153A": {"bns": "196", "offense": "Promoting Enmity", "min": "3 years", "max": "5 years"},
    "186": {"bns": "221", "offense": "Obstructing Public Servant", "min": "3 months", "max": "3 months"},
    "193": {"bns": "229", "offense": "False Evidence", "min": "7 years", "max": "7 years"},
    "201": {"bns": "238", "offense": "Causing disappearance of evidence", "min": "7 years", "max": "Life Imprisonment"},
    "304A": {"bns": "106", "offense": "Death by Negligence", "min": "2 years", "max": "5 years"},
    "304B": {"bns": "80", "offense": "Dowry Death", "min": "7 years", "max": "Life Imprisonment"},
    "308": {"bns": "110", "offense": "Attempt Culpable Homicide", "min": "3 years", "max": "7 years"},
    "363": {"bns": "137", "offense": "Kidnapping", "min": "7 years", "max": "7 years"},
    "364": {"bns": "140", "offense": "Kidnapping for Murder", "min": "Life Imprisonment", "max": "Death"},
    "366": {"bns": "142", "offense": "Kidnapping Woman to compel marriage", "min": "10 years", "max": "10 years"},
    "376A": {"bns": "66", "offense": "Rape causing death/vegetative state", "min": "20 years", "max": "Death"},
    "376D": {"bns": "70", "offense": "Gang Rape", "min": "20 years", "max": "Life Imprisonment"},
    
    # Expanded database-driven mappings
    "149": {"bns": "190", "offense": "Common Object Liability", "min": "Same as main offense", "max": "Same as main offense"},
    "148": {"bns": "191(3)", "offense": "Rioting with Deadly Weapon", "min": "Fine", "max": "5 years"},
    "147": {"bns": "191(2)", "offense": "Rioting", "min": "Fine", "max": "2 years"},
    "306": {"bns": "108", "offense": "Abetment of Suicide", "min": "Fine", "max": "10 years"},
    "409": {"bns": "316(3)", "offense": "CBT by Public Servant", "min": "10 years", "max": "Life Imprisonment"},
    "279": {"bns": "281", "offense": "Rash Driving", "min": "Fine", "max": "6 months"},
    "452": {"bns": "333", "offense": "House Trespass with Preparation to Hurt", "min": "Fine", "max": "7 years"},
    "341": {"bns": "126(1)", "offense": "Wrongful Restraint", "min": "Fine", "max": "1 month"},
    "342": {"bns": "127", "offense": "Wrongful Confinement", "min": "Fine", "max": "1 year"},
    "494": {"bns": "82", "offense": "Marrying again during lifetime", "min": "Fine", "max": "7 years"},
    "394": {"bns": "309(4)", "offense": "Hurt in committing robbery", "min": "10 years", "max": "Life Imprisonment"},
    "397": {"bns": "309(6)", "offense": "Robbery/Dacoity with attempt to cause death/hurt", "min": "7 years", "max": "10 years"},
    "84": {"bns": "22", "offense": "Act of person of unsound mind", "min": "None", "max": "None"},
    "300": {"bns": "101", "offense": "Murder definition", "min": "Same as main offense", "max": "Same as main offense"},
    "299": {"bns": "100", "offense": "Culpable homicide definition", "min": "Same as main offense", "max": "Same as main offense"},
    "415": {"bns": "318", "offense": "Cheating definition", "min": "Same as main offense", "max": "Same as main offense"},
    "511": {"bns": "62", "offense": "Attempting to commit offences", "min": "Same as main offense", "max": "Same as main offense"},
    
    # Common database typo overrides
    "3048": {"bns": "80", "offense": "Dowry Death", "min": "7 years", "max": "Life Imprisonment"},
    "1208": {"bns": "61", "offense": "Criminal Conspiracy", "min": "6 months", "max": "Life Imprisonment"}
}
